### ISSUE TITLE
Add 'matrix' support to group.Sync/Async actors

### ISSUE THREAD

**Issue by diranged** [Nextdoor/kingpin#143]
New tracking issue for the suggested `Matrix` actor proposed in issue #72: https://github.com/Nextdoor/kingpin/issues/72#issuecomment-62028051

**Comment by diranged** [comment]
This is done, right @siminm?

**Comment by siminm** [comment]
Done in what sense? No code exists for executing same actor with an array of inputs.

**Comment by diranged** [comment]
Nevermind ... you're right, we havn't started work on this. Lets chat about it today.

**Comment by siminm** [comment]
@diranged here's the example of combining Information passing ( #173 ) and an iterating actor (from #72 )

```json
{ "desc": "Notify many rooms",
  "actor": "group.Async",
  "inputs": [
    { "room": "engineering", "message": "Dinner is here"},
    { "room": "systems", "message": "Dinner is here"},
    { "room": "oncall", "message": "Dinner is here"}
  ],
  "output_name": "Notify",
  "acts": [
    { "desc": "Notify {Notify.room}",
      "actor": "misc.Hipchat",
      "depends_on": "Notify",
      "options": {
        "room": "{Notify.room}",
        "message": "{Notify.message}"
      }
    }
  ]
}
```
