### ISSUE TITLE
Should the `aws` base actor pull meta-data from Amazons Metadata service?

### ISSUE THREAD

**Issue by diranged** [Nextdoor/kingpin#185]
Although most of the time, Kingpin is being used remotely on a server that may or may not be in Amazon ... sometimes it may be used on a host that IS in amazon, and the actors may need information about the local instance. (#184 is a good example).

It would be interesting if the `aws.BaseActor` could pull from [Amazons MetaData Service](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-categories) and automatically gather this data.

There are two ways we can do this, I think..

**At Actor Instantiation Time**
This would cause the app to block momentarily while the API is called ... which is fundamentally bad in our model. However, its structurally very simple. The `__init__()` method could determine that it was missing information (ie, access key .. instance ID, whatever the actor needs), and attempt to reach the API service to get the information.

**At Kingpin Instantiation Time**
There could be a flag (`--get-ec2-metadata`?) that causes the `deploy.py` script to go out and get all the meta data, and then standard script parsing is handled with additional tokens that were discovered via this call. Effectively the EC2 meta data is appended to the `os.environ()` data before the script is parsed. This method is probably faster (only one call to the API service .. and happens very early on in the process), but is just slightly more complex to understand.

Thoughts?

**Comment by diranged** [comment]
By the way, this code would act similarly if a host was in GCE instead. Though we don't yet have GCE actors, it would be trivial to add them.

**Comment by diranged** [comment]
Oh, and if we did a pre-check for metadata, we could pass it in through the contextual token system as well.

**Comment by siminm** [comment]
If we already had information passing then it would be just a separate actor such as `aws.GetMetaData` and the results would go into the context of subsequent actors.

Since we don't have it, I don't see a need to create any new syntax, or kingpin flags. The wrapper that invokes kingpin would simply do this:

```bash
export SELF_INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
kingping join_elb.json
```

**Comment by diranged** [comment]
Hmm... Ok, I actually agree with this. I think you're right about the information passing. Lets keep this ticket around (I'll remove the milestone though) as a reference.
