### ISSUE TITLE
AWS Actors should convert Zones into Regions

### ISSUE THREAD

**Issue by diranged** [Nextdoor/kingpin#198]
When a `zone` (eg. `us-west-1a`) is supplied to the `region` setting of Kingpin, we should simply convert it by stripping off the `a`.

**Comment by siminm** [comment]
I'd vote against it. It's too implicit, and this behavior should be handled by the authoring script. Issue #199  should handle this case better. Meanwhile I've added the following line to our RightScript:

```bash
export ELB_ZONE=${EC2_PLACEMENT_AVAILABILITY_ZONE%?}  # remove last character
```
