### ISSUE TITLE
Add "rolling" execution to Async actor

### ISSUE THREAD

**Issue by siminm** [Nextdoor/kingpin#219]
If an Async actor has hundreds of actions it would be great to throttle/roll out the executions. Consider adding a new option:

```json
{ "options": {
    "acts": ["..."],
    "roll": 10
  }
}
```

**Comment by diranged** [comment]
I agree -- this would be a really nice feature. May or may not be worth actually subclassing `group.Async` into `group.RollingAsync`

**Comment by siminm** [comment]
Closed via #273 and #278
