### ISSUE TITLE
New Actor: rightscale.server_array.RollingRelaunch

### ISSUE THREAD

**Issue by diranged** [Nextdoor/kingpin#222]
It would be pretty useful to have a Kingpin actor that could walk through a SeverArray and execute a rolling-relaunch of all the hosts in that array. I could imagine it looking like this:

```json5
{ "desc": "Replace all of our WWW Hosts, two at a time",
  "actor": "rightscale.server_array.RollingRelaunch",
  "options": {
    "array": "prod-www-uswest1",
    "concurrent": 2
  }
}
```

**Comment by siminm** [comment]
I'd name it just  `Relaunch`, and make `concurrent` optional. Other than that lgtm.

**Comment by diranged** [comment]
Since this can actually be done purely in Kingpin JSON scripts now (see #228), closing it.
