### ISSUE TITLE
rightscale.server_array.Launch should catch Stranded instances

### ISSUE THREAD

**Issue by mikhail** [Nextdoor/kingpin#297]
If a fleet is launched, but 1 instance is strnaded, Kingpin could Launch 1 more instance so that it finally reaches the minimum count that it's waiting for.

**Comment by siminm** [comment]
bump

**Comment by siminm** [comment]
cc: @stovoy

**Comment by siminm** [comment]
Add `"retry_stranded": 1` to rightscale.server_array.Launch actor

Retry should be global, not per instance

**Comment by diranged** [comment]
Just as a reminder -- if the array is `enabled`, then this happens automatically by RightScale. Are you trying to solve the case where we're launching instances  without enabling the array? Or are we trying to speedup the process?

I think it could get dangerous to have Kingpin auto-relaunching things if the underlying servers are stranding for some reason.

**Comment by siminm** [comment]
For situations when arrays are disabled (common case @ nextdoor) nothing relaunches the stranded server, and nothing fails. So kingpin run just hangs. Since this is an optional parameter - the danger is offloaded onto the developer
