### ISSUE TITLE
aws.elb.registerinstance should allow multiple ELB names.

### ISSUE THREAD

**Issue by mikhail** [Nextdoor/kingpin#300]

**Comment by maazghani** [comment]
This applies to both classic ELBs and ELBv2 correct? Said differently, goal is to allow multiple ELB names *and* multiple ARNs for ELBv2?

**Comment by diranged** [comment]
> This applies to both classic ELBs and ELBv2 correct? Said differently, goal is to allow multiple ELB names _and_ multiple ARNs for ELBv2? I know this issue was created prior to v2 but can the above be inferred if addressed now.

Truth be told - this project is mostly on life-support at this point. We use it heavily internally, but we use it almost exclusively to manage CloudFormation stacks. We welcome pull requests, but I am not likely to add in this feature myself, or improve that part of the code base.

(Seriously, would love to have other people contribute.. happy to review and provide help!)

**Comment by maazghani** [comment]
I had a random urge to brush up on my python aws sdk muscle memory and this seems like an appropriate place, so happy to contribute here. Hope to share something soon!

**Comment by maazghani** [comment]
I had a random urge to brush up on my python aws sdk muscle memory and this seems like an appropriate place, so happy to contribute here. I imagine understanding the hulls of this tool will remain important internally, until I imagine it will soon become a company fisc as the (work)loads are kingpinctl’d to k5n or the like; whatever the next voyage into abstraction netes.
