### ISSUE TITLE
Provide a @dry method wrapper

### ISSUE THREAD

**Issue by diranged** [Nextdoor/kingpin#345]
We find ourselves frequently writing methods like this:

```
@gen.coroutine
def _create_user(self, user):
  if self._dry:
    self.log.warning('Would have created user %s' % user)
    raise gen.Return()

  yield self.thread(self.iam_conn, create_user, user)
```

It would be awesome if instead we provided a wrapper:
```
@gen.coroutine
@dry('Would have created user %s' % self.option('user'))
def _create_user(self)
  yield self.thread(self.iam_conn, create_user, user)
```

This would remove a ton of stupid unit tests, and be much more reusable.. and ... DRY. :)

**Comment by siminm** [comment]
I see the desire here, but something feels wrong. Additionally variable `self` isn't available until after you're in the function. Maybe you could get the following syntax working...

`@dry('Would have created user {user}')` and then rely on some `.format()` function in python to pass the correct variables

**Comment by siminm** [comment]
Something like.... [THIS](https://github.com/Nextdoor/kingpin/pull/346)
